/**
 * Portugal's 308 municipalities, with the Tax Authority's district/council
 * code (the "DT/CC" used on the Modelo 22). Generated from the derrama
 * circular, which lists every one of them; the names are the circular's,
 * in normal case.
 *
 * Kept apart from the rates so the search box in the settings can load the
 * names without the tax tables.
 */

export interface Municipality {
  /** District + council, e.g. "0813" for Silves. */
  code: string;
  name: string;
  district: string;
}

export const MUNICIPALITIES: Municipality[] = [
  { code: '0101', name: 'Águeda', district: 'Aveiro' },
  { code: '0102', name: 'Albergaria-a-Velha', district: 'Aveiro' },
  { code: '0103', name: 'Anadia', district: 'Aveiro' },
  { code: '0104', name: 'Arouca', district: 'Aveiro' },
  { code: '0105', name: 'Aveiro', district: 'Aveiro' },
  { code: '0106', name: 'Castelo de Paiva', district: 'Aveiro' },
  { code: '0107', name: 'Espinho', district: 'Aveiro' },
  { code: '0108', name: 'Estarreja', district: 'Aveiro' },
  { code: '0109', name: 'Santa Maria da Feira', district: 'Aveiro' },
  { code: '0110', name: 'Ílhavo', district: 'Aveiro' },
  { code: '0111', name: 'Mealhada', district: 'Aveiro' },
  { code: '0112', name: 'Murtosa', district: 'Aveiro' },
  { code: '0113', name: 'Oliveira de Azeméis', district: 'Aveiro' },
  { code: '0114', name: 'Oliveira do Bairro', district: 'Aveiro' },
  { code: '0115', name: 'Ovar', district: 'Aveiro' },
  { code: '0116', name: 'S. João da Madeira', district: 'Aveiro' },
  { code: '0117', name: 'Sever do Vouga', district: 'Aveiro' },
  { code: '0118', name: 'Vagos', district: 'Aveiro' },
  { code: '0119', name: 'Vale de Cambra', district: 'Aveiro' },
  { code: '0201', name: 'Aljustrel', district: 'Beja' },
  { code: '0202', name: 'Almodôvar', district: 'Beja' },
  { code: '0203', name: 'Alvito', district: 'Beja' },
  { code: '0204', name: 'Barrancos', district: 'Beja' },
  { code: '0205', name: 'Beja', district: 'Beja' },
  { code: '0206', name: 'Castro Verde', district: 'Beja' },
  { code: '0207', name: 'Cuba', district: 'Beja' },
  { code: '0208', name: 'Ferreira do Alentejo', district: 'Beja' },
  { code: '0209', name: 'Mértola', district: 'Beja' },
  { code: '0210', name: 'Moura', district: 'Beja' },
  { code: '0211', name: 'Odemira', district: 'Beja' },
  { code: '0212', name: 'Ourique', district: 'Beja' },
  { code: '0213', name: 'Serpa', district: 'Beja' },
  { code: '0214', name: 'Vidigueira', district: 'Beja' },
  { code: '0301', name: 'Amares', district: 'Braga' },
  { code: '0302', name: 'Barcelos', district: 'Braga' },
  { code: '0303', name: 'Braga', district: 'Braga' },
  { code: '0304', name: 'Cabeceiras de Basto', district: 'Braga' },
  { code: '0305', name: 'Celorico de Basto', district: 'Braga' },
  { code: '0306', name: 'Esposende', district: 'Braga' },
  { code: '0307', name: 'Fafe', district: 'Braga' },
  { code: '0308', name: 'Guimarães', district: 'Braga' },
  { code: '0309', name: 'Póvoa do Lanhoso', district: 'Braga' },
  { code: '0310', name: 'Terras de Bouro', district: 'Braga' },
  { code: '0311', name: 'Vieira do Minho', district: 'Braga' },
  { code: '0312', name: 'Vila Nova de Famalicão', district: 'Braga' },
  { code: '0313', name: 'Vila Verde', district: 'Braga' },
  { code: '0314', name: 'Vizela', district: 'Braga' },
  { code: '0401', name: 'Alfândega da Fé', district: 'Bragança' },
  { code: '0402', name: 'Bragança', district: 'Bragança' },
  { code: '0403', name: 'Carrazeda de Ansiães', district: 'Bragança' },
  { code: '0404', name: 'Freixo Espada À Cinta', district: 'Bragança' },
  { code: '0405', name: 'Macedo de Cavaleiros', district: 'Bragança' },
  { code: '0406', name: 'Miranda do Douro', district: 'Bragança' },
  { code: '0407', name: 'Mirandela', district: 'Bragança' },
  { code: '0408', name: 'Mogadouro', district: 'Bragança' },
  { code: '0409', name: 'Torre de Moncorvo', district: 'Bragança' },
  { code: '0410', name: 'Vila Flor', district: 'Bragança' },
  { code: '0411', name: 'Vimioso', district: 'Bragança' },
  { code: '0412', name: 'Vinhais', district: 'Bragança' },
  { code: '0501', name: 'Belmonte', district: 'Castelo Branco' },
  { code: '0502', name: 'Castelo Branco', district: 'Castelo Branco' },
  { code: '0503', name: 'Covilhã', district: 'Castelo Branco' },
  { code: '0504', name: 'Fundão', district: 'Castelo Branco' },
  { code: '0505', name: 'Idanha-a-Nova', district: 'Castelo Branco' },
  { code: '0506', name: 'Oleiros', district: 'Castelo Branco' },
  { code: '0507', name: 'Penamacor', district: 'Castelo Branco' },
  { code: '0508', name: 'Proença-a-Nova', district: 'Castelo Branco' },
  { code: '0509', name: 'Sertã', district: 'Castelo Branco' },
  { code: '0510', name: 'Vila de Rei', district: 'Castelo Branco' },
  { code: '0511', name: 'Vila Velha de Ródão', district: 'Castelo Branco' },
  { code: '0601', name: 'Arganil', district: 'Coimbra' },
  { code: '0602', name: 'Cantanhede', district: 'Coimbra' },
  { code: '0603', name: 'Coimbra', district: 'Coimbra' },
  { code: '0604', name: 'Condeixa-a-Nova', district: 'Coimbra' },
  { code: '0605', name: 'Figueira da Foz', district: 'Coimbra' },
  { code: '0606', name: 'Góis', district: 'Coimbra' },
  { code: '0607', name: 'Lousã', district: 'Coimbra' },
  { code: '0608', name: 'Mira', district: 'Coimbra' },
  { code: '0609', name: 'Miranda do Corvo', district: 'Coimbra' },
  { code: '0610', name: 'Montemor-o-Velho', district: 'Coimbra' },
  { code: '0611', name: 'Oliveira do Hospital', district: 'Coimbra' },
  { code: '0612', name: 'Pampilhosa da Serra', district: 'Coimbra' },
  { code: '0613', name: 'Penacova', district: 'Coimbra' },
  { code: '0614', name: 'Penela', district: 'Coimbra' },
  { code: '0615', name: 'Soure', district: 'Coimbra' },
  { code: '0616', name: 'Tábua', district: 'Coimbra' },
  { code: '0617', name: 'Vila Nova de Poiares', district: 'Coimbra' },
  { code: '0701', name: 'Alandroal', district: 'Évora' },
  { code: '0702', name: 'Arraiolos', district: 'Évora' },
  { code: '0703', name: 'Borba', district: 'Évora' },
  { code: '0704', name: 'Estremoz', district: 'Évora' },
  { code: '0705', name: 'Évora', district: 'Évora' },
  { code: '0706', name: 'Montemor-o-Novo', district: 'Évora' },
  { code: '0707', name: 'Mora', district: 'Évora' },
  { code: '0708', name: 'Mourão', district: 'Évora' },
  { code: '0709', name: 'Portel', district: 'Évora' },
  { code: '0710', name: 'Redondo', district: 'Évora' },
  { code: '0711', name: 'Reguengos de Monsaraz', district: 'Évora' },
  { code: '0712', name: 'Vendas Novas', district: 'Évora' },
  { code: '0713', name: 'Viana do Alentejo', district: 'Évora' },
  { code: '0714', name: 'Vila Viçosa', district: 'Évora' },
  { code: '0801', name: 'Albufeira', district: 'Faro' },
  { code: '0802', name: 'Alcoutim', district: 'Faro' },
  { code: '0803', name: 'Aljezur', district: 'Faro' },
  { code: '0804', name: 'Castro Marim', district: 'Faro' },
  { code: '0805', name: 'Faro', district: 'Faro' },
  { code: '0806', name: 'Lagoa', district: 'Faro' },
  { code: '0807', name: 'Lagos', district: 'Faro' },
  { code: '0808', name: 'Loulé', district: 'Faro' },
  { code: '0809', name: 'Monchique', district: 'Faro' },
  { code: '0810', name: 'Olhão', district: 'Faro' },
  { code: '0811', name: 'Portimão', district: 'Faro' },
  { code: '0812', name: 'S. Brás de Alportel', district: 'Faro' },
  { code: '0813', name: 'Silves', district: 'Faro' },
  { code: '0814', name: 'Tavira', district: 'Faro' },
  { code: '0815', name: 'Vila do Bispo', district: 'Faro' },
  { code: '0816', name: 'Vila Real Sto. António', district: 'Faro' },
  { code: '0901', name: 'Aguiar da Beira', district: 'Guarda' },
  { code: '0902', name: 'Almeida', district: 'Guarda' },
  { code: '0903', name: 'Celorico da Beira', district: 'Guarda' },
  { code: '0904', name: 'Figueira C. Rodrigo', district: 'Guarda' },
  { code: '0905', name: 'Fornos de Algodres', district: 'Guarda' },
  { code: '0906', name: 'Gouveia', district: 'Guarda' },
  { code: '0907', name: 'Guarda', district: 'Guarda' },
  { code: '0908', name: 'Manteigas', district: 'Guarda' },
  { code: '0909', name: 'Meda', district: 'Guarda' },
  { code: '0910', name: 'Pinhel', district: 'Guarda' },
  { code: '0911', name: 'Sabugal', district: 'Guarda' },
  { code: '0912', name: 'Seia', district: 'Guarda' },
  { code: '0913', name: 'Trancoso', district: 'Guarda' },
  { code: '0914', name: 'Vila Nova de Foz Côa', district: 'Guarda' },
  { code: '1001', name: 'Alcobaça', district: 'Leiria' },
  { code: '1002', name: 'Alvaiázere', district: 'Leiria' },
  { code: '1003', name: 'Ansião', district: 'Leiria' },
  { code: '1004', name: 'Batalha', district: 'Leiria' },
  { code: '1005', name: 'Bombarral', district: 'Leiria' },
  { code: '1006', name: 'Caldas da Rainha', district: 'Leiria' },
  { code: '1007', name: 'Castanheira de Pêra', district: 'Leiria' },
  { code: '1008', name: 'Figueiró dos Vinhos', district: 'Leiria' },
  { code: '1009', name: 'Leiria', district: 'Leiria' },
  { code: '1010', name: 'Marinha Grande', district: 'Leiria' },
  { code: '1011', name: 'Nazaré', district: 'Leiria' },
  { code: '1012', name: 'Óbidos', district: 'Leiria' },
  { code: '1013', name: 'Pedrógão Grande', district: 'Leiria' },
  { code: '1014', name: 'Peniche', district: 'Leiria' },
  { code: '1015', name: 'Pombal', district: 'Leiria' },
  { code: '1016', name: 'Porto de Mós', district: 'Leiria' },
  { code: '1101', name: 'Alenquer', district: 'Lisboa' },
  { code: '1102', name: 'Arruda dos Vinhos', district: 'Lisboa' },
  { code: '1103', name: 'Azambuja', district: 'Lisboa' },
  { code: '1104', name: 'Cadaval', district: 'Lisboa' },
  { code: '1105', name: 'Cascais', district: 'Lisboa' },
  { code: '1106', name: 'Lisboa', district: 'Lisboa' },
  { code: '1107', name: 'Loures', district: 'Lisboa' },
  { code: '1108', name: 'Lourinhã', district: 'Lisboa' },
  { code: '1109', name: 'Mafra', district: 'Lisboa' },
  { code: '1110', name: 'Oeiras', district: 'Lisboa' },
  { code: '1111', name: 'Sintra', district: 'Lisboa' },
  { code: '1112', name: 'Sobral de Monte Agraço', district: 'Lisboa' },
  { code: '1113', name: 'Torres Vedras', district: 'Lisboa' },
  { code: '1114', name: 'Vila Franca de Xira', district: 'Lisboa' },
  { code: '1115', name: 'Amadora', district: 'Lisboa' },
  { code: '1116', name: 'Odivelas', district: 'Lisboa' },
  { code: '1201', name: 'Alter do Chão', district: 'Portalegre' },
  { code: '1202', name: 'Arronches', district: 'Portalegre' },
  { code: '1203', name: 'Avis', district: 'Portalegre' },
  { code: '1204', name: 'Campo Maior', district: 'Portalegre' },
  { code: '1205', name: 'Castelo de Vide', district: 'Portalegre' },
  { code: '1206', name: 'Crato', district: 'Portalegre' },
  { code: '1207', name: 'Elvas', district: 'Portalegre' },
  { code: '1208', name: 'Fronteira', district: 'Portalegre' },
  { code: '1209', name: 'Gavião', district: 'Portalegre' },
  { code: '1210', name: 'Marvão', district: 'Portalegre' },
  { code: '1211', name: 'Monforte', district: 'Portalegre' },
  { code: '1212', name: 'Nisa', district: 'Portalegre' },
  { code: '1213', name: 'Ponte de Sor', district: 'Portalegre' },
  { code: '1214', name: 'Portalegre', district: 'Portalegre' },
  { code: '1215', name: 'Sousel', district: 'Portalegre' },
  { code: '1301', name: 'Amarante', district: 'Porto' },
  { code: '1302', name: 'Baião', district: 'Porto' },
  { code: '1303', name: 'Felgueiras', district: 'Porto' },
  { code: '1304', name: 'Gondomar', district: 'Porto' },
  { code: '1305', name: 'Lousada', district: 'Porto' },
  { code: '1306', name: 'Maia', district: 'Porto' },
  { code: '1307', name: 'Marco de Canaveses', district: 'Porto' },
  { code: '1308', name: 'Matosinhos', district: 'Porto' },
  { code: '1309', name: 'Paços de Ferreira', district: 'Porto' },
  { code: '1310', name: 'Paredes', district: 'Porto' },
  { code: '1311', name: 'Penafiel', district: 'Porto' },
  { code: '1312', name: 'Porto', district: 'Porto' },
  { code: '1313', name: 'Póvoa do Varzim', district: 'Porto' },
  { code: '1314', name: 'Santo Tirso', district: 'Porto' },
  { code: '1315', name: 'Valongo', district: 'Porto' },
  { code: '1316', name: 'Vila do Conde', district: 'Porto' },
  { code: '1317', name: 'Vila Nova de Gaia', district: 'Porto' },
  { code: '1318', name: 'Trofa', district: 'Porto' },
  { code: '1401', name: 'Abrantes', district: 'Santarém' },
  { code: '1402', name: 'Alcanena', district: 'Santarém' },
  { code: '1403', name: 'Almeirim', district: 'Santarém' },
  { code: '1404', name: 'Alpiarça', district: 'Santarém' },
  { code: '1405', name: 'Benavente', district: 'Santarém' },
  { code: '1406', name: 'Cartaxo', district: 'Santarém' },
  { code: '1407', name: 'Chamusca', district: 'Santarém' },
  { code: '1408', name: 'Constância', district: 'Santarém' },
  { code: '1409', name: 'Coruche', district: 'Santarém' },
  { code: '1410', name: 'Entroncamento', district: 'Santarém' },
  { code: '1411', name: 'Ferreira do Zêzere', district: 'Santarém' },
  { code: '1412', name: 'Golegã', district: 'Santarém' },
  { code: '1413', name: 'Mação', district: 'Santarém' },
  { code: '1414', name: 'Rio Maior', district: 'Santarém' },
  { code: '1415', name: 'Salvaterra de Magos', district: 'Santarém' },
  { code: '1416', name: 'Santarém', district: 'Santarém' },
  { code: '1417', name: 'Sardoal', district: 'Santarém' },
  { code: '1418', name: 'Tomar', district: 'Santarém' },
  { code: '1419', name: 'Torres Novas', district: 'Santarém' },
  { code: '1420', name: 'Vila Nova da Barquinha', district: 'Santarém' },
  { code: '1421', name: 'Ourém', district: 'Santarém' },
  { code: '1501', name: 'Alcácer do Sal', district: 'Setúbal' },
  { code: '1502', name: 'Alcochete', district: 'Setúbal' },
  { code: '1503', name: 'Almada', district: 'Setúbal' },
  { code: '1504', name: 'Barreiro', district: 'Setúbal' },
  { code: '1505', name: 'Grândola', district: 'Setúbal' },
  { code: '1506', name: 'Moita', district: 'Setúbal' },
  { code: '1507', name: 'Montijo', district: 'Setúbal' },
  { code: '1508', name: 'Palmela', district: 'Setúbal' },
  { code: '1509', name: 'Santiago do Cacém', district: 'Setúbal' },
  { code: '1510', name: 'Seixal', district: 'Setúbal' },
  { code: '1511', name: 'Sesimbra', district: 'Setúbal' },
  { code: '1512', name: 'Setúbal', district: 'Setúbal' },
  { code: '1513', name: 'Sines', district: 'Setúbal' },
  { code: '1601', name: 'Arcos de Valdevez', district: 'Viana do Castelo' },
  { code: '1602', name: 'Caminha', district: 'Viana do Castelo' },
  { code: '1603', name: 'Melgaço', district: 'Viana do Castelo' },
  { code: '1604', name: 'Monção', district: 'Viana do Castelo' },
  { code: '1605', name: 'Paredes de Coura', district: 'Viana do Castelo' },
  { code: '1606', name: 'Ponte da Barca', district: 'Viana do Castelo' },
  { code: '1607', name: 'Ponte de Lima', district: 'Viana do Castelo' },
  { code: '1608', name: 'Valença', district: 'Viana do Castelo' },
  { code: '1609', name: 'Viana do Castelo', district: 'Viana do Castelo' },
  { code: '1610', name: 'Vila Nova de Cerveira', district: 'Viana do Castelo' },
  { code: '1701', name: 'Alijó', district: 'Vila Real' },
  { code: '1702', name: 'Boticas', district: 'Vila Real' },
  { code: '1703', name: 'Chaves', district: 'Vila Real' },
  { code: '1704', name: 'Mesão Frio', district: 'Vila Real' },
  { code: '1705', name: 'Mondim de Basto', district: 'Vila Real' },
  { code: '1706', name: 'Montalegre', district: 'Vila Real' },
  { code: '1707', name: 'Murça', district: 'Vila Real' },
  { code: '1708', name: 'Peso da Régua', district: 'Vila Real' },
  { code: '1709', name: 'Ribeira de Pena', district: 'Vila Real' },
  { code: '1710', name: 'Sabrosa', district: 'Vila Real' },
  { code: '1711', name: 'Sta. Marta Penaguião', district: 'Vila Real' },
  { code: '1712', name: 'Valpaços', district: 'Vila Real' },
  { code: '1713', name: 'Vila Pouca de Aguiar', district: 'Vila Real' },
  { code: '1714', name: 'Vila Real', district: 'Vila Real' },
  { code: '1801', name: 'Armamar', district: 'Viseu' },
  { code: '1802', name: 'Carregal do Sal', district: 'Viseu' },
  { code: '1803', name: 'Castro Daire', district: 'Viseu' },
  { code: '1804', name: 'Cinfães', district: 'Viseu' },
  { code: '1805', name: 'Lamego', district: 'Viseu' },
  { code: '1806', name: 'Mangualde', district: 'Viseu' },
  { code: '1807', name: 'Moimenta da Beira', district: 'Viseu' },
  { code: '1808', name: 'Mortágua', district: 'Viseu' },
  { code: '1809', name: 'Nelas', district: 'Viseu' },
  { code: '1810', name: 'Oliveira de Frades', district: 'Viseu' },
  { code: '1811', name: 'Penalva do Castelo', district: 'Viseu' },
  { code: '1812', name: 'Penedono', district: 'Viseu' },
  { code: '1813', name: 'Resende', district: 'Viseu' },
  { code: '1814', name: 'Santa Comba Dão', district: 'Viseu' },
  { code: '1815', name: 'S. João da Pesqueira', district: 'Viseu' },
  { code: '1816', name: 'S. Pedro do Sul', district: 'Viseu' },
  { code: '1817', name: 'Sátão', district: 'Viseu' },
  { code: '1818', name: 'Sernancelhe', district: 'Viseu' },
  { code: '1819', name: 'Tabuaço', district: 'Viseu' },
  { code: '1820', name: 'Tarouca', district: 'Viseu' },
  { code: '1821', name: 'Tondela', district: 'Viseu' },
  { code: '1822', name: 'Vila Nova de Paiva', district: 'Viseu' },
  { code: '1823', name: 'Viseu', district: 'Viseu' },
  { code: '1824', name: 'Vouzela', district: 'Viseu' },
  { code: '1901', name: 'Angra do Heroismo', district: 'Angra do Heroismo' },
  { code: '1902', name: 'Calheta (Açores)', district: 'Angra do Heroismo' },
  { code: '1903', name: 'Santa Cruz Graciosa', district: 'Angra do Heroismo' },
  { code: '1904', name: 'Velas', district: 'Angra do Heroismo' },
  { code: '1905', name: 'Vila Praia da Vitória', district: 'Angra do Heroismo' },
  { code: '2001', name: 'Corvo', district: 'Horta' },
  { code: '2002', name: 'Horta', district: 'Horta' },
  { code: '2003', name: 'Lages das Flores', district: 'Horta' },
  { code: '2004', name: 'Lages do Pico', district: 'Horta' },
  { code: '2005', name: 'Madalena', district: 'Horta' },
  { code: '2006', name: 'Santa Cruz das Flores', district: 'Horta' },
  { code: '2007', name: 'S. Roque do Pico', district: 'Horta' },
  { code: '2101', name: 'Lagoa (Açores)', district: 'Ponta Delgada' },
  { code: '2102', name: 'Nordeste', district: 'Ponta Delgada' },
  { code: '2103', name: 'Ponta Delgada', district: 'Ponta Delgada' },
  { code: '2104', name: 'Povoação', district: 'Ponta Delgada' },
  { code: '2105', name: 'Ribeira Grande', district: 'Ponta Delgada' },
  { code: '2106', name: 'Vila Franca do Campo', district: 'Ponta Delgada' },
  { code: '2107', name: 'Vila Porto', district: 'Ponta Delgada' },
  { code: '2201', name: 'Calheta', district: 'Funchal' },
  { code: '2202', name: 'Câmara de Lobos', district: 'Funchal' },
  { code: '2203', name: 'Funchal', district: 'Funchal' },
  { code: '2204', name: 'Machico', district: 'Funchal' },
  { code: '2205', name: 'Ponta do Sol', district: 'Funchal' },
  { code: '2206', name: 'Porto Moniz', district: 'Funchal' },
  { code: '2207', name: 'Porto Santo', district: 'Funchal' },
  { code: '2208', name: 'Ribeira Brava', district: 'Funchal' },
  { code: '2209', name: 'Santa Cruz', district: 'Funchal' },
  { code: '2210', name: 'Santana', district: 'Funchal' },
  { code: '2211', name: 'S. Vicente', district: 'Funchal' },
];
